# YAML schema for GitHub Actions:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
#
# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/
#
#
# This file contains the workflows that are run periodically to build the examples.

name: CI

on: push

jobs:
  build:
    strategy:
      matrix:
        idf_ver: ["release-v4.4", "release-v5.0", "release-v5.3"]
        idf_target: ["esp32", "esp32s2", "esp32s3", "esp32c3"]
        include:
          - idf_ver: "release-v5.0"
            idf_target: "esp32c2"
          - idf_ver: "release-v5.3"
            idf_target: "esp32p4"
    runs-on: ubuntu-latest
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Build for ${{ matrix.idf_target }}
        env:
          IDF_TARGET: ${{ matrix.idf_target }}
        shell: bash
        working-directory: examples
        run: |
          . ${IDF_PATH}/export.sh
          ../scripts/build_examples.sh ${IDF_TARGET}
